services:
  pg:
    image: postgres:15-alpine
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./.db/data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - default
    user: "1000:1000"

  app:
    build:
      context: .
    ports:
      - "8000:80"
    env_file:
      - .env.docker
    depends_on:
      - pg
    networks:
      - default
    user: "1000:1000"